### ISSUE TITLE
"Alert" and "Mine" text are switched in megaping, and it makes the ui flash a bit when the radial menu is out

### ISSUE THREAD

**Issue by brandyyn** [GTMEGA/Ping#1]
"Alert" and "Mine" text are switched in megaping, and it makes the ui flash a bit when the radial menu is out
![image](https://github.com/GTMEGA/Ping/assets/11356565/1489ad23-11de-41c5-bfb8-7f4e6eb86263)
![image](https://github.com/GTMEGA/Ping/assets/11356565/34433b59-57dd-4ab5-b7c0-9f5b48ad32dc)

thank you for coming to my ted talk

**Comment by matt-159** [comment]
> it makes the ui flash a bit when the radial menu is out

are you pinging while another gui is open?

**Comment by brandyyn** [comment]
> > it makes the ui flash a bit when the radial menu is out
> 
> are you pinging while another gui is open?

nope just the hot bar and journey map flash, is it even possible to ping with a gui open?

**Comment by matt-159** [comment]
yes

**Comment by brandyyn** [comment]
> yes

It’s a very light flicker that occurs, I can record a video of it when I’m home
